server:
  port: 9527

spring:
  application:
    name: gateway-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    client:
      ipAddress: 127.0.0.1
zuul:
  retryable: true
  ignored-services: "*"
  add-host-header: true
  sensitive-headers: "*"
  routes:
    security-oauth2:
      stripPrefix: false
      path: /uaa/**
    security-oauth2-order:
      stripPrefix: false
      path: /order/**


eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
  client:
    serviceUrl:
      #eurekaServers
      defaultZone: http://127.0.0.1:8761/eureka

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env