server:
  port: 8761
spring:
  application:
    name: eureka
  cloud:
    client:
      ipAddress: 127.0.0.1
eureka:
  instance:
    #\u57FA\u4E8Eip\u914D\u7F6E
    prefer-ip-address: false
    #\u81EA\u5B9A\u4E49id
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #\u6CE8\u518C\u5230\u5176\u4ED6eureka
    registerWithEureka: false
    #\u4ECE\u5176\u4ED6eureka\u62C9\u53D6\u4FE1\u606F
    fetchRegistry: false
  server:
    #\u81EA\u6211\u4FDD\u62A4
    enable-self-preservation: false

ribbon:
  eureka:
    enabled: true