server:
  port: 8887
  servlet:
    context-path: /order


spring:
  application:
    name: security-oauth2-order
  main:
    allow-bean-definition-overriding: true
  cloud:
    client:
      ipAddress: 127.0.0.1

eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
  client:
    serviceUrl:
      #eurekaServers
      defaultZone: http://127.0.0.1:8761/eureka
